### ISSUE TITLE
Add missing ops

### ISSUE THREAD

**Issue by aborgna-q** [CQCL/tket-json-rs#30]
There are multiple operations missing (`CnY` , `CnZ`, `CSdg`, `PauliExpBox`, `ConjugationBox`, ...)

Compare https://github.com/CQCL/tket-json-rs/blob/main/src/optype.rs with https://github.com/CQCL/tket/blob/develop/tket/include/tket/OpType/OpType.hpp for the full list.

**Comment by CalMacCQ** [comment]
`OpType.Phase` is another one
